version: "3"

services:
  shitchen_kink:
    container_name: discord-shitchenkink
    build: "."
    restart: always
    environment:
      - "Bot__Auth__Token=${DISCORD_TOKEN}"
  mongodb:
    image: "mongo:5.0"
    restart: always
    volumes:
      - "./database:/data/db"